CREATE TABLE IF NOT EXISTS Categories (
  Id    INTEGER PRIMARY KEY AUTOINCREMENT,
  Name  TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Tags (
  Id    INTEGER PRIMARY KEY AUTOINCREMENT,
  Name  TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TodoItems (
  Id          INTEGER PRIMARY KEY AUTOINCREMENT,
  Title       TEXT NOT NULL,
  Description TEXT,
  DueDate     TEXT,
  Notes       TEXT,
  Status      INTEGER NOT NULL,
  Priority    INTEGER NOT NULL,
  CategoryId  INTEGER,
  FOREIGN KEY (CategoryId) REFERENCES Categories(Id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TodoItemTags (
  TodoItemId INTEGER NOT NULL,
  TagId      INTEGER NOT NULL,
  PRIMARY KEY (TodoItemId, TagId),
  FOREIGN KEY (TodoItemId) REFERENCES TodoItems(Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (TagId) REFERENCES Tags(Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_TodoItems_Status     ON TodoItems(Status);
CREATE INDEX IF NOT EXISTS IX_TodoItems_Priority   ON TodoItems(Priority);
CREATE INDEX IF NOT EXISTS IX_TodoItems_CategoryId ON TodoItems(CategoryId);
CREATE INDEX IF NOT EXISTS IX_TodoItems_DueDate    ON TodoItems(DueDate);
CREATE INDEX IF NOT EXISTS IX_TodoItemTags_TagId   ON TodoItemTags(TagId);
